"""add users table

Revision ID: f0bbb3feed63
Revises: 
Create Date: 2022-07-12 18:13:02.212686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bbb3feed63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_submit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_submit_email'), 'user_submit', ['email'], unique=False)
    op.create_index(op.f('ix_user_submit_message'), 'user_submit', ['message'], unique=False)
    op.create_index(op.f('ix_user_submit_name'), 'user_submit', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_submit_name'), table_name='user_submit')
    op.drop_index(op.f('ix_user_submit_message'), table_name='user_submit')
    op.drop_index(op.f('ix_user_submit_email'), table_name='user_submit')
    op.drop_table('user_submit')
    # ### end Alembic commands ###
